### ISSUE TITLE
Priority highlighting not working (Ubuntu)

### ISSUE THREAD

**Issue by gohma231** [davraamides/todotxt-mode#1] opened 2019-05-22 19:43 UTC
Priority highlighting does not work most of the time.  I don't know what information to give to help you out with this though.  I have attached a screenshot showing that the priorities do not highlight.

![todotxt_colorBug](https://user-images.githubusercontent.com/4106435/58203547-54c41f80-7ca8-11e9-8307-69202439434a.png)

**Comment by davraamides** [comment] 2019-05-22 19:45
HI,

Sorry, it's a mistake I accidentally committed and didn't notice right away. I will push the fix tonight and drop you a note.

-David

On May 22, 2019, at 3:43 PM, jgoulet1994 <notifications@github.com> wrote:

Priority highlighting does not work most of the time. I don't know what information to give to help you out with this though. I have attached a screenshot showing that the priorities do not highlight.

**Comment by gohma231** [comment] 2019-05-22 19:46
No worries.  This seems to be the only todotxt extension for VS Code that is actually working for Ubuntu users.  Thank you for the extension!

**Comment by davraamides** [comment] 2019-05-22 21:32
It's my first extension - and my first time using Typescript! So I'm just
learning but I'm using it every day so will keep on top of this.

**Comment by davraamides** [comment] 2019-05-23 00:24
This issue is resolved with v1.4.2. A bad regex was the cause.

**Closed as completed by davraamides** 2019-05-23 00:24 UTC
